CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR_IGNORECASE NOT NULL,
	LOGIN VARCHAR_IGNORECASE NOT NULL,
	NAME VARCHAR_IGNORECASE NOT NULL,
	BIRTHDAY DATE NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS (
    USER_ID1 INTEGER NOT NULL,
    USER_ID2 INTEGER NOT NULL,
    CONSTRAINT FRIENDS_PK PRIMARY KEY (USER_ID1, USER_ID2),
    CONSTRAINT FRIENDS_USERS_FK FOREIGN KEY (USER_ID1) REFERENCES PUBLIC.USERS(ID),
    CONSTRAINT FRIENDS_USERS_FK_1 FOREIGN KEY (USER_ID2) REFERENCES PUBLIC.USERS(ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.GENRES (
	GENRE_ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR_IGNORECASE NOT NULL,
	CONSTRAINT GENRES_PK PRIMARY KEY (GENRE_ID),
	CONSTRAINT GENRES_UNIQUE UNIQUE (NAME)
);
CREATE TABLE IF NOT EXISTS PUBLIC.RATING (
	RATING_ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR_IGNORECASE NOT NULL,
	CONSTRAINT RATING_PK PRIMARY KEY (RATING_ID),
	CONSTRAINT RATING_UNIQUE UNIQUE (NAME)
);
CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
	FILM_ID INTEGER NOT NULL AUTO_INCREMENT,
	FILM_NAME VARCHAR_IGNORECASE NOT NULL,
	DESCRIPTION VARCHAR_IGNORECASE NOT NULL,
	RELEASE_DATE DATE NOT NULL,
	DURATION INTEGER NOT NULL,
	ID_RATING INTEGER NOT NULL,
	CONSTRAINT FILMS_PK PRIMARY KEY (FILM_ID),
	CONSTRAINT FILMS_RATING_FK FOREIGN KEY (id_rating) REFERENCES PUBLIC.RATING(RATING_ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.FILM_LIKES (
	ID_FILM INTEGER NOT NULL,
	ID_USER INTEGER NOT NULL,
	CONSTRAINT FILMLIKES_PK PRIMARY KEY (ID_FILM,ID_USER),
	CONSTRAINT FILMLIKES_FILMS_FK FOREIGN KEY (ID_FILM) REFERENCES PUBLIC.FILMS(FILM_ID),
	CONSTRAINT FILMLIKES_USERS_FK FOREIGN KEY (ID_USER) REFERENCES PUBLIC.USERS(ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRES (
	ID_FILM INTEGER NOT NULL,
	ID_GENRE INTEGER NOT NULL,
	CONSTRAINT FILMGENRES_PK PRIMARY KEY (ID_FILM,ID_GENRE),
	CONSTRAINT FILMGENRES_FILMS_FK FOREIGN KEY (ID_FILM) REFERENCES PUBLIC.FILMS(FILM_ID),
	CONSTRAINT FILMGENRES_GENRES_FK FOREIGN KEY (ID_GENRE) REFERENCES PUBLIC.GENRES(GENRE_ID)
);